name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    name: Ruff Linting
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        run: apt install python3
        
   

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff linter
        run: ruff .  # or ruff src/ if you want to scope it

    
