name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    name: Ruff Linting
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff linter
        run: ruff .  # or ruff src/ if you want to scope it

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: lint  # only build Docker image if linting passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: false  # ❗ Set to true if you want to push images
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-image-name:latest .

      # - name: Push Docker image
      #   run: docker push my-image-name:latest